# -*- coding: utf-8 -*-
"""Credit card fraud detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TWLtgi8uLQZur2jUVTHuCM-MgapIZQ4o
"""

from google.colab import files
uploaded = files.upload()

file_name = list(uploaded.keys())[0]
print("Uploaded file:", file_name)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv("/content/credit_card_fraud_200_rows.csv")

print("Shape:", data.shape)
data.head()

print(data.info())
print("\nMissing values:\n", data.isnull().sum())

data = data.sample(frac=0.1, random_state=48)
print("Sampled Shape:", data.shape)

fraud = data[data['Is_Fraud'] == 1]
valid = data[data['Is_Fraud'] == 0]

print("Fraud Cases:", len(fraud))
print("Valid Cases:", len(valid))

plt.figure(figsize=(10,6))
sns.scatterplot(x='Time', y='Amount', hue='Is_Fraud', data=data)
plt.title('Time vs Amount (Fraud vs Non-Fraud)')
plt.show()

plt.figure(figsize=(12,9))
sns.heatmap(data.corr(numeric_only=True), vmax=0.8, square=True)
plt.title("Correlation Heatmap")
plt.show()

X = data.drop(['Is_Fraud', 'Transaction_ID'], axis=1)
Y = data['Is_Fraud']

# Identify categorical columns and apply one-hot encoding
categorical_cols = X.select_dtypes(include=['object']).columns
X = pd.get_dummies(X, columns=categorical_cols, drop_first=True)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.35, stratify=Y, random_state=42
)

# Re-running train_test_split to ensure X_train, X_test, y_train, y_test are defined
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.35, stratify=Y, random_state=42
)

from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    class_weight='balanced'
)

rf_model.fit(X_train, y_train)

y_pred = rf_model.predict(X_test)

from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nAccuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

y_prob = rf_model.predict_proba(X_test)[:,1]

y_pred_new = (y_prob > 0.3).astype(int)

print("Improved Confusion Matrix:\n", confusion_matrix(y_test, y_pred_new))
print("\nImproved Classification Report:\n", classification_report(y_test, y_pred_new))

